### ISSUE TITLE
User Experience Enhancement (Copywriting, navigation)

### ISSUE THREAD

**Issue by Faralha** [nmFaizz/flexoo-revamp#1]
Copywriting:
Saran, ubah title dari "Apakah kamu memerlukan website untuk tugas, lomba, event, atau bisnis kamu?" menjadi lebih pendek seperti: "Butuh website untuk tugas, lomba, event, atau bisnis?"

Navigation:
Tombol kuning Tentang kami di awal lebih baik langsung diarahkan ke halaman pemesanan/google form "Ajukan Projek" agar lebih intuitif bagi calon pelanggan

**Comment by nmFaizz** [comment]
don bang 😋
